### ISSUE TITLE
MB self skillchains

### ISSUE THREAD

**Issue by gwbischof** [ekrividus/autoMB#1]
Thanks for the great script.
I noticed that it doesn't MB skillchains that I close.
I think this could be a useful feature.
I will try to figure out how to update it.

**Comment by ekrividus** [comment]
So this is likely as simple as adding a delay for instance
//amb delay 3
As it defaults to a delay much lower than the animation lock time for a WS. 
I think I have mine ~2.5 on Nin for bursting w/ Ni and San spells.
If you happen to be trying to use Burst Affinity or Pet Abilities however, those don't work as I never bothered with them due to the general lack of use in most content.
If you find that adding a delay still doesn't work I'd be happy to try to dig into the why of it.
It may also be worth toggling on spell names and/or a few other bits of info for debug purposes.
//amb toggle spell
