### ISSUE TITLE
ninjutsu not bursting

### ISSUE THREAD

**Issue by maxlink89** [ekrividus/autoMB#14]
getting an error on line 387 when i have it set to tier 3 of jutsu on ninja not sure if i messed something up or what

**Comment by ekrividus** [comment]
Can you share what the error says?
I'm not sure without more information if this is a bug or a oopsie in a setting.

**Comment by maxlink89** [comment]
I will when I get hone just headed out to go to sister's for a few day will retest on Sunday and give you a screen shot of the error

**Comment by maxlink89** [comment]
https://i.imgur.com/ViaFC6P.png
is the error i hope it helps

**Comment by maxlink89** [comment]
think i figure out the issues it was a oops on my end i had it set to nin not jutsu
ninja attacks so fast with auto sc i dont get a chance to sc with it
when the cor trust i chained with him i was able to burst 
damn surper attack speed on nin lol

**Comment by enfarious** [comment]
I think that might be fixed in the newest version. Fair warning, however, I haven't had an active account since Nov. so my changes are not totally vetted. I do have a few friends that still test things for me and they haven't mentioned any issues with the newest code. 
It was, until a few mins. ago, only in a private repo. I just pushed it so if you want to try it out it's there. If you want to play safe(er) I'd copy the autoMB you currently have to autoMB.old before snagging the latest version.
If you're using my autoSC there's a delay you can add for just that reason. Having my BLM, GEO, and SCH miss MBs and my NIN just never get to cast cause of how fast some things would fire led me to have lots and lots of delay options. Even autoMB has one for opening and double bursts because some spell tiers cast so fast it was causing them to fail lol.

**Comment by ekrividus** [comment]
Oh, good to know and thank you :)

**Comment by Darsch82** [comment]
Just a heads up, I Beleive ninjutsu is not magic bursting because the ma command being called is not formatted properly.  I was just using AMB and it was calling /ma "Hyoton:Ichi" <t> resulting in  a command error has occurred message when it should be calling /ma "Hyoton: Ichi" <t>  with a space between the : and ichi.

**Comment by ekrividus** [comment]
Thanks for letting me know. Just pushed a change that should fix that. Please let me know if it is still not behaving as expected.

**Comment by Darsch82** [comment]
> Thanks for letting me know. Just pushed a change that should fix that. Please let me know if it is still not behaving as expected.

Working perfectly from what I have seen so far now.
