### ISSUE TITLE
Straight up does not work

### ISSUE THREAD

**Issue by BubbaKush99** [ekrividus/autoMB#16]
I load up the addon, turn it on via "//amb on" and it does nothing when I SC. Using GEO, many skill chains and no MB, no casting, nothing.

Either I am missing something here or this addon is broken.

**Comment by ekrividus** [comment]
It's certainly possible that an update broke this addon. I haven't played in some time now and as a result I don't see the day to day of any of my addons anymore.
That being that.
If you can give me a bit more information like:
Did you use the debug command? `//amb debug`
Did you use any of the show info commands? `//amb show spell` for instance
If you did were they printing anything to your log?
If they weren't printing anything then I'd list my active addons to see if it loaded properly to begin with. `//addon list`

If the addon is loaded and it is showing that it is trying to find a spell but failing to, then please let me know what the actual messages are. It could be that, and this would be odd but you know, it is trying to find a helix or jutsu when you're a GEO which is fixable with `//amb cast spell` 

If you have explored all of those things and it still isn't printing/doing anything then I'd say it's potentially been broken by a change to a memory/data structure in the game so that the way packets present no longer works for this addon. That'd be a shame and hasn't happened in a very long time, but it can happen. If that's the case I'm afraid I may not have an easy fix.

**Comment by Mercurian** [comment]
It functions still, but -Ra spells don't fully. You still haven't fixed them I guess? 

Using it right now.

**Comment by BubbaKush99** [comment]
Does not work for me still.

I load up the addon just fine and then I do "//amb on" and is says activating.

When I do "//amb debug" it tells me it is it will show info but that's it.

When I type "//amb show" it shows info saying it is on.

The default is on spell.

I was doing scission skillchains on urganites and no MB attempt, no debug info, no action. If it still works then I do not know what I am doing wrong.

**Comment by ekrividus** [comment]
> It functions still, but -Ra spells don't fully. You still haven't fixed them I guess?
> 
> Using it right now.

Nah I haven't played in well over a year now so no meaningful work gets done these days. Someday I'll wander back like I always do though.

> I was doing scission skillchains on urganites and no MB attempt, no debug info, no action. If it still works then I do not know what I am doing wrong.

If it isn't printing anything when a SC goes off then it either isn't activating properly, which would be super strange and not what I expect is the issue, or it isn't actually detecting the SC. Can you post your settings file for me?

**Comment by BubbaKush99** [comment]
see settings file below. Since my GEO is not the one involved in the SC would that be a reason why it is not detecting a SC?

`<?xml version="1.1" ?>
<settings>
    <global>
        <cast_delay>0.25</cast_delay>
        <cast_range>22</cast_range>
        <cast_tier>1</cast_tier>
        <cast_type>spell</cast_type>
        <change_target>true</change_target>
        <check_day>false</check_day>
        <check_weather>false</check_weather>
        <disable_on_zone>false</disable_on_zone>
        <double_burst>false</double_burst>
        <double_burst_delay>1</double_burst_delay>
        <frequency>10</frequency>
        <gearswap>false</gearswap>
        <mp>100</mp>
        <show_bonus_elements>false</show_bonus_elements>
        <show_elements>false</show_elements>
        <show_skillchain>false</show_skillchain>
        <show_spell>false</show_spell>
        <step_down>0</step_down>
        <useAOE>false</useAOE>
    </global>
</settings>`

**Comment by ekrividus** [comment]
Nothing funky in that. You've got me at a loss. 
Are you loading/starting the addon when your party is at camp or are you loading/starting it when you first login? It turns itself off when zoning cause when it doesn't it does very bot-like things.

**Comment by BubbaKush99** [comment]
I reloaded/restarted it before I started SCing and still nothing. Is it possible that other add-ons could be interfering with this addon? Or maybe a prerequisite addon that it needs?

**Comment by Mercurian** [comment]
You have it set to t1 spell, do you not have stone 1 spell?

If you don't, it can't cast what you don't have lol

**Comment by ekrividus** [comment]
> I reloaded/restarted it before I started SCing and still nothing. Is it possible that other add-ons could be interfering with this addon? Or maybe a prerequisite addon that it needs?

I don't know of any other addons that would interfere with packet reading. Some could if they cancel spells for you, Idk of any though. If you have `//amb show all` or `//amb debug on` going it should always at least post to the chat that it detected a SC even if literally every other step of selecting a spell, swapping targets if needed, and casting fail. If it isn't printing any of that with `//amb debug on` then I'd delete the folder and drop it in again. I mean you don't hear of many corrupt dls but it is possible. 

And yeah I didn't even think about the cast tier and if the spell(s) are learned. I always just assume everyone has everything cause of how easy they all are to get now. Change the spell tier to cast to 4, 5, 6 or w/e and see if it still happens.

**Comment by defster** [comment]
It seems like the addon has trouble detecting skillchains. It only detects the ones i start or close myself, and even then it feels a bit hit or miss. My trusts will happily chain with no detection in log/debug.

**Comment by ekrividus** [comment]
See https://github.com/ekrividus/autoMB/issues/17#issuecomment-2056552558

**Comment by BubbaKush99** [comment]
It is working now. Thank you!
